name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Deta CLI
        shell: bash
        run: curl -fsSL https://get.deta.dev/cli.sh | sh

      - name: Clone Deta Micro
        shell: bash
        run: |
          export DETA_ACCESS_TOKEN=${{ secrets.DETA_ACCESS_TOKEN }}
          mkdir -p tmp/deta-bot
          ~/.deta/bin/deta clone --name deta-bot --project default tmp/deta-bot
          cp -r tmp/deta-bot/.deta .
          rm -rf tmp

      - name: Deploy to Deta Micro
        shell: bash
        run: |
          export DETA_ACCESS_TOKEN=${{ secrets.DETA_ACCESS_TOKEN }}
          ~/.deta/bin/deta deploy purge-dependencies
          ~/.deta/bin/deta deploy

      - name: Ping the endpoint
        shell: bash
        run: |
          curl -X 'GET' \
            'https://deta-server.deta.dev/' \
