name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Deta CLI & set Deta Access Token as a env var
        shell: bash
        run: curl -fsSL https://get.deta.dev/cli.sh | sh
             echo '/home/runner/.deta/bin' >> $GITHUB_PATH
             echo "DETA_ACCESS_TOKEN=${{ secrets.DETA_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Clone Deta Micro
        shell: bash
        run: |
          mkdir -p tmp/deta-bot
          deta clone --name deta-bot --project default tmp/deta-bot
          cp -r tmp/deta-bot/.deta .
          rm -rf tmp

      - name: Deploy to Deta Micro
        shell: bash
        run: |
          deta deploy

      - name: Ping the endpoint
        shell: bash
        run: |
          curl -X 'GET' \
            'https://deta-server.deta.dev/'
